### PR TITLE
Fix contributing links

### LINKED ISSUE #154: Links need to be fixed in CONTRIBUTING.md
The Contributing Guide, `CONTRIBUTING.md`, contains two links with URLs that should be updated:

1. the _How to Contribute to an Open Source Project on GitHub_ link leads to a 404 and should be updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
2. the `[repo]` link reference currently points to a placeholder URL (https://example.com/FIXME) and should be updated to point to the source repository for the lesson (i.e. this GitHub repository).

The Contributing Guide is one of the files that is unique to each repository - to allow for individual lesson projects to define their own guidance for contributors - so unfortunately this is not an issue that can be fixed centrally e.g. by updating the template files in the lesson infrastructure. Instead the file must be updated in the individual lesson repositories themselves.

### PR DESCRIPTION
**Pull request by JCSzamosi**
Addressing the broken links raised by @tobyhodges in #154.

This also makes the change to the "issues" list discussed in that same thread. I'm requesting @zkamvar review it before I make a similar PR to the template repo so that I only have to make changes in one place.

fixes #154

### CODE REVIEW

**Comment by JCSzamosi** [comment]
If @zkamvar approves the "issues list" change and can point me to a list of repos that have been converted to Workbench, I am happy to create similar PRs for those repos in addition to the template repo.

**Comment by zkamvar** [comment]
HI @JCSzamosi, thank you so much! I agree that the "issues list" phrasing is a very sensible change.

You can find a list of repositories that have been transitioned in https://carpentries.github.io/workbench/transition-schedule.html 

They are also listed as [issue titles in the lesson transition repository](https://github.com/carpentries/lesson-transition/issues?q=is%3Aissue+is%3Aclosed+label%3Alesson), so you can use the GitHub API to retrieve a machine-readable list:

```
GET /repos/carpentries/lesson-transition/issues?status=closed&label=lesson
```

**Comment by JCSzamosi** [comment]
Thank you @zkamvar!

I know best practice says PRs should not be proposed and approved by the same maintainer, so I'm going to give it a couple days for another @datacarpentry/organization-genomics-maintainers maintainer to merge this.

In the mean time, I will create PRs for the template repo and existing, transitioned repos

**Comment by hidyverse** [comment]
Thanks for being on top of this @JCSzamosi

**Comment by JCSzamosi** [comment]
Since no one has objected in the past several days, I'm going to merge this now.

**Pull request merged**
