### PR TITLE
update zenodo json for lesson release

### PR DESCRIPTION
**Pull request by tobyhodges**
updating the `.zenodo.json` with metadata about contributors since last release, in preparation for the infrastructure transition.

### CODE REVIEW

**Comment by JCSzamosi** [comment]
@tobyhodges if you do not mind terribly changing my name from JCSzamosi to Jake C. Szamosi, I will happily merge the pull request.  I can merge before that happens also, but we'll have to change it eventually so might as well be now.

**Comment by JCSzamosi** [comment]
I suppose I can make the change myself but then I think the rules say someone else will have to merge the pull request?

Edit: I made the change. Since this seems like not a huge deal I will merge the request in a few hours if I see no objections.

**Comment by hoytpr** [comment]
Looks fine to me.

**Comment by tobyhodges** [comment]
> @tobyhodges if you do not mind terribly changing my name from JCSzamosi to Jake C. Szamosi, I will happily merge the pull request. I can merge before that happens also, but we'll have to change it eventually so might as well be now.

@JCSzamosi thank you for going ahead and making the change yourself - this was definitely the right way to go. 

For context, you were being listed by your GitHub username because of the preference you have indicated on your profile in The Carpentries community database, [AMY](https://amy.carpentries.org/). You can update that preference any time, which will give you some other options to specify how you would like to be listed in future lesson publications. They should be happening (much) more frequently from now on, so it may well be worth the time 😁

**Comment by JCSzamosi** [comment]
Oh good to know! I have not really looked at any settings in AMY recently! I will go do that.

**Pull request merged**
