### PR TITLE
Hoyt fix

### PR DESCRIPTION
**Pull request by hoytpr**
Changed the _config.yml file to match a (mostly) earlier version and the config.yml from the wrangling genomics lesson after other updates to the YAML headers (like deleting the permalinks), had also changed the CSS rendering. This _config.yml worked fine on my test site at:
https://hoytpr.github.io/organization-genomics-test/

and rendered as expected at:
https://hoytpr.github.io/organization-genomics-test/CODE_OF_CONDUCT.html
https://hoytpr.github.io/organization-genomics-test/setup.html
https://hoytpr.github.io/organization-genomics-test/reference.html
https://hoytpr.github.io/organization-genomics-test/aio.html

### CODE REVIEW

**Comment by hoytpr** [comment]
Reopened after checking title. @tracykteal

**Comment by hoytpr** [comment]
Reopening after undoing (or redoing) the forced push. Should be at e93a201  now where it works as described in test repo after I issue new PR

**Comment by hoytpr** [comment]
GitHub still drives me bonkers, but at least learning continues. When rendered on my local machine, I also got a warning message:
"Invalid theme folder: _includes"
In case that is helpful to anyone. I've made progress with themes, but this message is a mystery to me.

**Comment by tracykteal** [comment]
I cannot at all figure out why, but I had to replace the section from line 65 to line 81, with that section from another file to get it to render locally. I used lines 65 from 81 from https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/_config.yml. There must be some invisible formatting that's there that I can't see to fix. With that update, it rendered locally and I ran it through [YAML Lint](http://www.yamllint.com/) and it checked out there too.

**Comment by hoytpr** [comment]
Might be (probably) Windows EOL (cr-lf) as I was also copy pasting. 

If you did not get the error "Invalid theme folder: _includes" I think it's okay to merge. Although I should probably test a local rendering first. Let me get onto my desktop and give that a try. Thanks Tracy!
=p

**Comment by tracykteal** [comment]
Your update works! Thanks for all the work on this. I'll go ahead and merge.

**Comment by hoytpr** [comment]
Thanks Tracy @tracykteal 
The local render gave an error: "jekyll 3.8.5 | Error:  (C:/Users/Hoyt/git/Saved/organization-genomics/_config.yml): did not find expected '-' indicator while parsing a block collection at line 67 **column 3**"

Just had to look close at those lines to see the extra space. Thanks very much! Closes #79

**Pull request merged**
