### PR TITLE
update size of NCBI-SRA

### PR DESCRIPTION
**Pull request by tobyhodges**

### CODE REVIEW

**Comment by hoytpr** [comment]
This certainly looks good to me! Thanks! It is mixed with issue #98 so we'll need to get all the wording to match up carefully. @tracykteal

**Comment by tobyhodges** [comment]
Should have given my source in the original PR. I got the number from here: https://www.ncbi.nlm.nih.gov/sra/docs/sragrowth/

**Comment by hoytpr** [comment]
Can you add that link to the number with your PR?

**Comment by tobyhodges** [comment]
Done :+1:

**Comment by tracykteal** [comment]
So much data! Quite the increase from 2014. Thanks for the update.

**Comment by hoytpr** [comment]
Thanks @tobyhodges, Great contribution. Thanks @tracykteal !

**Pull request merged**
