### PR TITLE
Be generic about search engine

### PR DESCRIPTION
**Pull request by tobyhodges**
"Google" -> "an Internet search engine"

Feel free to reject this if you don't worry about Google's quiet march to dominance as much as I do :)

### CODE REVIEW

**Comment by hoytpr** [comment]
Understanding your feelings, but how about "Google or another internet search engine".  There might be old folks like me who (unlike me) only know of one internet search engine. This provides them the *required* info, while also educating them that Google isn't the only one.

**Comment by tobyhodges** [comment]
Thanks for your thoughts, Pete. I've updated the PR accordingly.

**Comment by hoytpr** [comment]
LGTM. @tracykteal

**Comment by tracykteal** [comment]
Thanks @tobyhodges and @hoytpr. Both good points. Looks good.

**Pull request merged**
